
【日志时间】：2020-11-06 10:08:07.4587 
【接口地址】：http://localhost/api/Account/GetUser 
【错误信息】：Attempted to divide by zero. 
【堆栈信息】：System.DivideByZeroException: Attempted to divide by zero.
   at NetCore.Fast.WebApi.Controllers.AccountController.GetUser() in E:\数字岩土\MyGit\MyStudySpace\NetCore.Fast\NetCore.Fast.App\NetCore.Fast.WebApi\Controllers\AccountController.cs:line 49
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
 

【日志时间】：2020-11-06 10:23:18.2364 
【接口地址】：http://localhost/api/Account/Login 
【错误信息】：[{"Field":"Username","Message":"The 用户名 field is required."}] 
【堆栈信息】： 
 

【日志时间】：2020-11-06 10:26:03.9649 
【接口地址】：http://localhost/api/Account/Login 
【错误信息】：[{"Field":"Username","Message":"The 用户名 field is required."}] 
【堆栈信息】： 
 

【日志时间】：2020-11-06 10:26:40.8742 
【接口地址】：http://localhost/api/Account/Login 
【错误信息】：[{"Field":"Username","Message":"The 用户名 field is required."}] 
【堆栈信息】： 
 

【日志时间】：2020-11-06 10:32:48.3509 
【接口地址】：http://localhost/api/Account/Login 
【错误信息】：[{"Field":"Username","Message":"The 用户名 field is required."}] 
【堆栈信息】： 
 

【日志时间】：2020-11-06 10:33:31.0497 
【接口地址】：http://localhost/api/Account/GetUser 
【错误信息】：Attempted to divide by zero. 
【堆栈信息】：System.DivideByZeroException: Attempted to divide by zero.
   at NetCore.Fast.WebApi.Controllers.AccountController.GetUser() in E:\数字岩土\MyGit\MyStudySpace\NetCore.Fast\NetCore.Fast.App\NetCore.Fast.WebApi\Controllers\AccountController.cs:line 49
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) 
 
